import { Footer } from "@/components/ui/Footer"
import { Header } from "@/components/ui/Header"
import { Toaster } from "@/components/ui/toaster"
import Providers from "@/providers/Providers"
import { Metadata } from "next"
import { Inter } from "next/font/google"
import { Suspense } from "react"
import { PuffLoader } from "react-spinners"
import "ui/globals.css";
const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}
export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html className="scroll-smooth" lang="en">
            <body className={inter.className + " dark"}>
                <Suspense
                    fallback={
                        <div className="h-screen flex items-center justify-center">
                            <PuffLoader />
                        </div>
                    }
                >
                    <Providers>
                        <Header />
                            <main>{children}</main>
                        <Footer />
                    </Providers>
                    <Toaster />
                </Suspense>
            </body>
        </html>
    )
}
