import { Footer } from "@/components/ui/Footer";
import { Header } from "@/components/ui/Header";
import { type Metadata } from "next";
import "ui/globals.css";
import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <Header />
      <main>
        {children}
      </main>
      <Footer />
    </>
  )
}
