import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "ui/globals.css"
import { cn } from "ui/lib/utils"
import "./globals.css"
import Providers from "@/providers/providers"
import { Toaster } from "@/components/ui/toaster"
import axios from "axios"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
    }) {
    return (
        <html lang="en">
            <body className={cn(inter.className, "dark")}>
                <Providers>
                    <main>{children}</main>
                    <Toaster />
                </Providers>
            </body>
        </html>
    )
}
