import 'ui/globals.css';
import "./globals.css";
import { Header } from "../components";
import { Footer } from "../components";
import { HydrateQueryClientProvider } from "@/providers";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="dark">
        <Header />
        <main className="site-main">
          <HydrateQueryClientProvider>
            {children}
          </HydrateQueryClientProvider>
        </main>
        <Footer />
      </body>
    </html>
  )
}
