import { HydrateQueryClientProvider } from "@/providers";
import "ui/globals.css";
import { Footer, Header } from "../components";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="dark">
        <Header />
        <main className="site-main">
          <HydrateQueryClientProvider>
            {children}
          </HydrateQueryClientProvider>
        </main>
        <Footer />
      </body>
    </html>
  )
}
