import { Toaster } from "@/components/ui/toaster"
import Providers from "@/providers/providers"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "ui/globals.css"
import { cn } from "ui/lib/utils"

const inter = Inter({ subsets: ["latin", "cyrillic"] })

import { Locale } from "../../../i18n.config"
import { LanguageSwitch } from "@/components/ui/language-switch"
import { getDictionary } from "@/lib/dictionary"

// export async function generateStaticParams() {
//     return i18n.locales.map((locale) => ({ lang: locale }))
// }

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default async function RootLayout({
    children,
    params,
}: {
    children: React.ReactNode
    params: { lang: Locale }
}) {
    const langInfo = await getDictionary(params.lang)
    return (
        <html lang={params.lang}>
            <body className={cn(inter.className, "dark")}>
                <Providers>
                    <LanguageSwitch lang={langInfo} />
                    <main>{children}</main>
                    <Toaster />
                </Providers>
            </body>
        </html>
    )
}
